# Generated by Django 4.1.4 on 2022-12-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ("id",)},
        ),
    ]
